### ISSUE TITLE
Enhance the "List" endpoint to support query by different attributes

### ISSUE THREAD

**Issue by ghaidaak98** [CSCI-GA-2820-SP24-003/promotions#28]
**As a** promotion manager
**I need** to query Promotions by type, start_date, status, product_id  of the Promotion
**So that** group promotions easily
   
 ### Details and Assumptions
 * Add different functions for querying Promotions by type, start_date and product_id of the Promotion
 * Add query capability to the model
 * Add query string support to the List function
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given type
 When calling List with the type
 Then shows all promotions of this type
```
 ```gherkin
 Given start_date
 When calling List with start_date
 Then shows all promotions starting on this date
```

 ```gherkin
 Given product_id
 When calling List with a  product_id
 Then shows all promotions related with this product
```

**Comment by QwertyQwh** [comment]
After some research I removed status from the story since for that query we need to either

1. have a db column dedicated for status.
2. use the sqlalchemy native datetime representation. 

Since we don't have the field and we are using python datetime for start date and duration, the filter wouldn't be able to calculate active/expired status from the two fields.
